### ISSUE TITLE
Ζωντανή ροή Τηλεκρήτη σε m3u8

### ISSUE THREAD

**Issue by ghost** [komhsgr/m3u#2]
Καλησπέρα Κόμη !
Εδώ και δύο εβδομάδες, το Τηλεκρήτη άρχισε ζωντανή ροή
Το λινκ αυτο https://telekriti.com πώς θα παίζει σε m3u8???
Ευχαριστώ

**Comment by ghost** [comment]
Όποιος έχει υπολογιστή, πατήστε το F12 στο πρόγραμμα περιήγησής σας για να ξεκινήσετε τα Εργαλεία προγραμματιστή και να το ορίσετε στην καρτέλα Δίκτυο. Επιστρέψτε στα κύρια παράθυρα του προγράμματος περιήγησης (επανα)φορτώστε τη σελίδα και παίξτε το βίντεο. Η διεύθυνση URL m3u8 θα εμφανιστεί στην κίνηση του δικτύου.

Σημειώστε ότι δεν θα χρησιμοποιούν όλα τα βίντεο ροής ένα αρχείο m3u8. Κάποιοι θα χρησιμοποιήσουν mpd, mp4 κ.λπ.

**Comment by ghost** [comment]
https://neon.streams.gr:8081/telekriti/index.m3u8

**Comment by komhsgr** [comment]
το προσθεσα ηδη στην νεα εφαρμογη GREEK TV ευχαριστω

**Comment by ghost** [comment]
Στο greekstreamtv ήθελα
