### ISSUE TITLE
Βρέθηκε λύση για τα κανάλια σε παρόχους

### ISSUE THREAD

**Issue by ghost** [komhsgr/m3u#3]
Twitch
Θεσσαλία TV - www.thessaliatv.gr
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/thessaliatv.m3u8
Center TV - www.centertv.gr
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/centertv.m3u8
Ροδόπη TV - www.tvrodopi.gr 
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/TVRodopi.m3u8 (Όταν λειτουργήσει η ροή δοκίμασε το, δεν δουλεύει αυτή την στιγμή)
Star Βορείου Ελλάδος 
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvstarfm.m3u8
Βεργίνα TV - www.verginanews.gr
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/verginachannel.m3u8
TV Κόσμος - www.tvkosmos.gr
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvkosmosgr.m3u8
(λογικά) Flash TV - www.flash-tv.gr
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/FlashTV.m3u8
Lepanto - www.lepantotvr.gr
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/LePanto.m3u8
Δίον TV - www.diontv.gr
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/DionTvKentrikisMakedonias.m3u8
Dailymotion
Euronews - gr.euronews.com
https://raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/Euronews_Greece.m3u8
Κόμη μου, είναι πίο εύκολα να τα βρίσκεις εύκολα πάρα να τα παλεύεις τόση ώρα.

**Comment by ghost** [comment]
Και σε enigma2 (greekstreamtv)
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/thessaliatv.m3u8:Θεσσαλία 
#DESCRIPTION Θεσσαλία 
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/centertv.m3u8:Center 
#DESCRIPTION Center 
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/TVRodopi.m3u8:Ροδόπη
#DESCRIPTION Ροδόπη
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvstarfm.m3u8:Star Δράμας
#DESCRIPTION Star Δράμας
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/verginachannel.m3u8:Βεργίνα
#DESCRIPTION Βεργίνα
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/tvkosmosgr.m3u8:Κόσμος
#DESCRIPTION Κόσμος
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/FlashTV.m3u8:Flash (?)
#DESCRIPTION Flash (?)
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/LePanto.m3u8:Lepanto
#DESCRIPTION Lepanto
#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/DionTvKentrikisMakedonias.m3u8:Δίον 
#DESCRIPTION Δίον
#SERVICE 5001:0:1:0:0:0:0:0:0:0:https%3a//raw.githubusercontent.com/azgaresncf/strm2hls/main/streams/Euronews_Greece.m3u8:Euronews Backup
#DESCRIPTION Euronews Backup

**Comment by komhsgr** [comment]
Γιατί να τα βάλεις ετσι στον ENIGMA 2 την στιγμή που παιζουν έτσι χωρις πατέντες

#EXTINF:5760 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-name="kosmos" tvg-logo="https://i.imgur.com/dMavjyG.png",TV KOSMOS
http://127.0.0.1:88/https://www.twitch.tv/tvkosmosgr
#EXTINF:-1 group-title="WEB TV" tvg-name="" tvg-logo="",XTV
http://127.0.0.1:88/https://www.twitch.tv/xtvision
#EXTINF:5350 group-title="WEB TV" tvg-logo="",TOP CHANNEL 
http://127.0.0.1:88/https://www.twitch.tv/topchannelkozani
#EXTINF:5044 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-name="" tvg-logo="https://i.imgur.com/pX9UBuZ.jpg",PRO NEWS 
http://127.0.0.1:88/https://www.twitch.tv/pronewstv
#EXTINF:5760 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-name="kosmos" tvg-logo="https://i.imgur.com/dMavjyG.png",TV KOSMOS
http://127.0.0.1:88/https://www.twitch.tv/tvkosmosgr
#EXTINF:4240 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-logo="",VERGINA TV
http://127.0.0.1:88/https://www.twitch.tv/verginachannel
#EXTINF:4260 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-logo="",DION TV
http://127.0.0.1:88/https://www.twitch.tv/diontvkentrikismakedonias
#EXTINF:4120 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-logo="",STAR BE
http://127.0.0.1:88/https://www.twitch.tv/tvstarfm
#EXTINF:6005 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-logo="",FLASH TV
http://127.0.0.1:88/https://www.twitch.tv/flashtvgr
#EXTINF:5950 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-logo="",ASTRA TV
http://127.0.0.1:88/https://www.twitch.tv/astratv2021
#EXTINF:5710 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-name="" tvg-logo="",CENTER TV
http://127.0.0.1:88/https://www.twitch.tv/centertv
#EXTINF:5955 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-name="" tvg-logo="",THESSALIA TV
http://127.0.0.1:88/https://www.twitch.tv/thessaliatv
#EXTINF:4530 group-title="ΠΕΡΙΦΕΡΕΙΑΚΑ" tvg-name="" tvg-logo="https://i.imgur.com/8qLqTaK.jpg",LEPANTO 
http://127.0.0.1:88/https://www.twitch.tv/lepantotv
#EXTINF:-1 group-title="WEB TV" tvg-logo="",CΙΝΕΜΑ ΤIME
http://127.0.0.1:88/https://www.twitch.tv/cinematimetv
#EXTINF:-1 group-title="WEB TV" tvg-logo="",IONIA TV
http://127.0.0.1:88/https://www.twitch.tv/tvioniathessalonikis
#EXTINF:-1 group-title="WEB TV" tvg-logo="",DTP
http://127.0.0.1:88/https://www.twitch.tv/dtpylias
#EXTINF:-1 group-title="WEB TV" tvg-logo="",MARON TV
http://127.0.0.1:88/https://www.twitch.tv/marontvgr

**Comment by ghost** [comment]
Μήπως αυτά τα λινκς να τα βάλεις στην νέα εφαρμογή?

**Comment by komhsgr** [comment]
H νέα εφαρμογή αν δείς τα έχει ολα ήδη και αλλα τόσα.

**Comment by ghost** [comment]
Μήπως να τα κάνεις αρχείο ως android.m3u όπως τα είχες κάποτε?

**Comment by komhsgr** [comment]
Aυτο το αρχείο διαγράφηκε δεν υπάρχει λόγος να υπάρχει διότι καταργηθηκε η παλια εφαρμογή.

**Comment by ghost** [comment]
Ευχαριστώ.

**Comment by komhsgr** [comment]
BERGINA TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Bergina.m3u8
CENTER TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Center.m3u8
DION TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Dion.m3u8
EURONEWS
https://raw.githubusercontent.com/komhsgr/m3u/main/Euronewsgr.m3u8
FLASH TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Flash.m3u8
KOSMOS TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Kosmos.m3u8
LEPANTO TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Lepanto.m3u8
STAR B.E.
https://raw.githubusercontent.com/komhsgr/m3u/main/Star.m3u8
THESSALIA TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Thessalia.m3u8
CINEMA TIME
https://raw.githubusercontent.com/komhsgr/m3u/main/Cinematime.m3u8
PRO NEWS
https://raw.githubusercontent.com/komhsgr/m3u/main/pronews.m3u8
IONIA TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Tvionia.m3u8
ASTRA TV
https://raw.githubusercontent.com/komhsgr/m3u/main/Astra.m3u8


Kαι δεν ειναι λύση δεν παιζουν συνέχεια. απλα πατέντα ειναι

**Comment by ghost** [comment]
Κάθε 3, 4 μπορεί και 5 ώρες αλλάζουν τα λινκς

**Comment by komhsgr** [comment]
Oποτε δεν ειναι λυση . ανοησια ειναι τα ειχα δοκιμάσει και εγω άπειρες φορες

**Comment by ghost** [comment]
Εγώ για το Astra έχω αυτό:
https://ssh101.bozztv.com/ssh101/astratv/playlist.m3u8
Για το Top έχω αυτό:
http://eu1.vectromdigital.com:1935/topchannel/topchannel/playlist.m3u8
και για το Cinema Time έχω αυτό:
https://s1.cystream.net/live/34100/playlist.m3u8
Τέλος μην μου δείχνεις το Ιωνία TV γιατί σε εμένα δεν λειτούργησε ποτέ 
Το Pronews αλλάζει συνεχώς το λινκ του που έχω και αυτή τη στιγμή που μιλάω είναι με:
http://di-8j1efme9.leasewebultracdn.com/p/3403/live/prolive.m3u8
Τέλος πάντων, σε ευχαριστώ πολύ! Ευτυχώς που υπάρχει το Twitch σε m3u8 (Δεν έχει συνεχώς δικό του λινκ αλλά αλλάζει συνεχώς κάθε μισή ώρα η κάθε 2, 3 η 4 ώρες)
Θέλω καινούργια ενημέρωση εάν βρείς το λινκ του Ροδόπη όταν λειτουργήσει.
