### ISSUE TITLE
Βοήθειαααααααααααααα!!!!

### ISSUE THREAD

**Issue by ghost** [komhsgr/m3u#4]
Όλα τα κυπριακά δουλεύουν κανονικά, αλλά Alpha Κύπρου, Capital, One Κύπρου, Plus και Βεργίνα Κύπρου δεν μου ανοίγουν.
Βλέπω αυτά που κατέγραψες:
https://l4.cloudskep.com/alphacyp/acy/playlist.m3u8
https://s1.cystream.net/live/capital/playlist.m3u8
https://s1.cystream.net/live/extra/playlist.m3u8
https://s1.cystream.net/live/plus/playlist.m3u8
https://s1.cystream.net/live/verginacy/playlist.m3u8
Αλλά δυστυχώς δεν μου ανοίγουν. Γιατί δεν μου ανοίγουν αυτά τα λινκς. Στα συγκεκριμένα λινκς είχα βάλει και Token ούτε και εκεί δεν λειτουργούν. Ούτε με VPN στην Κύπρο. Πρέπει να μου στείλεις τα λινκς που έχεις για τα 5 κανάλια. Νομίζω όταν το Capital και το Extra ήτανε δωρεάν το 2019 νομίζω (http://master.cystreams.com:25461/live/greek/asshole/14.ts η http://master.cystreams.com:25461/live/greek/asshole/15.ts) δεν είχαμε κανένα θέμα. Για το Smile, το Φάρος TV1, το Φάρος TV2 και το 34100 που εκπέμπουν από το ίδιο πάροχο δεν έχουμε κάποιο θέμα. Αλλά στο Smile αργεί να ανοίξει και μετά ανοίγει κατευθείαν. Θέλω να βρώ τα λινκς των Alpha Κύπρου, Capital, One Κύπρου, Plus και Βεργίνα Κύπρου
Πάμε στα ελληνικά μας.
Το Formedia TV διακόπηκε γιατί ενημερώνεται η ιστοσελίδα του σταθμού, όταν ολοκληρωθούν οι κατασκευές της ιστοσελίδας του σταθμόυ ελπίζω να μου στείλεις το νέο λινκ.
Το Εγνατία γιατί διακόπηκε, ωστόσο και το ITV? κάποτε όταν έπαιζε στο ustream.tv το ITV είχε πολύ ωραίο live streaming.
Το ORT το ξέρω γιατί διακόπηκε επειδή ανοιγοκλείνουν το live streaming
Επίσης, γιατί διακόπηκε το Twitch του Euro? Τους πήρα τηλέφωνο τις προάλλες και μου είπαν ότι υπάρχει πρόβλημα με το ίντερνετ, δεν μπορούμε να κάνουμε άλλο live streaming αμά ληφθεί το θέμα τούτο.
Επίσης έχω και ένα πρόβλημα με το Μακεδονία TV, όταν το ανοίγω το βλέπω πρώτα σε 180p, μετά από 3 δευτερόλεπτα σε 540p, μετά από 10 δευτερόλεπτα σε 720p και μετά εμφανίζεται κανονικά σε 1080p και το κάνει ανάποδα (720,540,180) και μετά το κάνει κάπως έτσι (180,540,720,1080). Στο ANT1 που εκπέμπει στο ίδιο πάροχο (cloudfront.net), όταν το ανοίγω δεν έχει καν θέμα.
Να μου λύσεις τις απορίες γιατί ανησυχώ.

**Comment by komhsgr** [comment]
Εχω αναφέρει οτι στην νεα εφαρμογή ο player ειναι δικια μας κατασκευης και οχι τους ετοιμους που έχουν άλλες εφαρμογές 
το μεγάλο προνόμιο σε αυτο τον player ειναι οτι ξεκλειδώνει οτιδίποτε ειναι με κλειδια.
  Τα κυπριακα έχουν κλειδια που αλλάζουν συνέχεια token οποτε οτι και να σου δωσω οτι και να κανεις δεν θα παιξουν πουθενά.Αλλα και να έπαιζαν εσυ εισαι ικανος να τα βγάλεις αριστερα δεξια σε λιστες οπως κανεις συνεχεια και μας εχεις κανει ρεζιλι στο iptv.org 

Formedia Θα επανέλθει οταν τελιωσουν οι εργασίες στην σελιδα τους.
ΕGNATIA TV το τελευταιο διαστημα μας κάνει περίεργα μια ερχεται μια φευγει.
Για το ITV ίδιες ανοησιες και εκει, τους εστειλα email μπας και κανουν σε twitch tv η  ssh101 σαν λύση απαντηση καμια.
ΟΡΤ μια δουλευει μια δεν δουλευει οποτε αγανάκτησα και δεν το ξαναέβαλα
EURO TV και τόσο καιρο που δουλεψε απο θαύμα ειναι, τωρα δικαιολογια το internet λες και δεν εχουν 23 ευρω το μηνα για internet τοσα βγαζουν απο διαφημίσεις.
Για το θεμα ΜΑΚ θα το δώ διοτι εκει τα πράγματα ειναι μυστηρια με αυτους.

Πρωσπαθω να πεισω το 
SUPER TV KORINTHOS
VOLCANO
KOS TV 
BHMA TV

Nα κανουν live streaming κανουν ηδη μεσο fb μπας και τους καταφέρω

**Comment by ghost** [comment]
Το Volcano θυμάμαι εκπέμπε το 2018 σε live streaming. Εγώ θέλω να κάνουν Live streaming τα:
- Achaia Channel
- Next TV
- Κώς TV
- Ένα Λαμίας
- Atlas TV
- Πατρίδα TV
Θυμάμαι ένα διάστημα που εκπέμπε στο Dailymotion το Atlas είχε πολύ καλό live streaming. Επίσης το Alert έχει μέτριο live streaming και το Ίριδα κολλάει συνεχως.

**Comment by ghost** [comment]
Εγώ θυμάμαι στο ssh101 κάποτε εκπέμπαν μεγάλος πληθυσμός τηλεοπτικών καναλιών. Θυμάμαι έστελνα μηνύματα στο Ένα Λαμίας και τούς έκανα ρεζίλι γιατί δεν έχουν live streaming και εκείνοι μου είπαν ότι να μήν στέλνω αλλά μηνύματα γιατί κάνω την ίδια ερώτηση κάθε μέρα. Επίσης το Star Λαμίας έχει καλό streaming στο castr αλλά μου την έσπαγε στο Dailymotion γιατί άλλαζε κάθε μέρα live streaming.

**Comment by ghost** [comment]
Γειά σου Κόμη. Είδα ότι άρχισε live streaming το Atlas TV αλλά η εικόνα του κάνει σπασίματα. Θέλω το λινκ σε m3u8 γιατί δεν βρίσκεται στο atlastv.gr/live

**Comment by ghost** [comment]
Θέλω να μου το στείλεις να το προσθέσω είναι το καλύτερο περιφερειακό κανάλι

**Comment by komhsgr** [comment]
Oχι Νικο το βλεπεις και απο την εφαρμογή μου μια χαρά.

**Comment by ghost** [comment]
Εγώ χρειάζομαι το λινκ σε m3u8 Γιώργο

**Comment by komhsgr** [comment]
Να πάρεις android box να βλεπεις απο εκει και να μην χρειάζεσαι m3u8

**Comment by ghost** [comment]
Είχα κάποτε android box αλλά δεν υπήρχε κανένα ελληνικό κανάλι

**Comment by ghost** [comment]
Το λινκ του Atlas χρειάζομαι σε m3u8

**Comment by komhsgr** [comment]
Δεν δίνω τίποτα οτι θελεις μονο απο την εφαρμογη θα το βλεπεις.

**Comment by ghost** [comment]
Εντάξει σε ευχαριστώ....

**Comment by komhsgr** [comment]
Οκ εβγαλες τα ρικ δημοσια το πηραν χαμπάρι και τα κλειδωσαν και αυτά. Χάρηκες τώρα, ευχαριστήθηκες?  Ρε καλά κάνω και δεν σας ξαναδίνω τίποτα.

**Comment by ghost** [comment]
Εδώ και χρόνια τα κλείδωσαν μάταια τους έβαλα. Επίσης κλείδωσαν παρά πολλά κανάλια και από την Ελλάδα και από την Κύπρο.

**Comment by komhsgr** [comment]
Ρε μην μου το παιζεις αθωα περιστερα, Ειναι καταγεγραμενο δημοσια οτι πρωτος εσυ εβγαλες τα LINK απο ΡΙΚ δημόσια απο υβριδικη τηλεοραση, Επι μηνες τα κρυβαμε και εσυ ο χαλβας τα εβγαλες δημόσια.Που θα μου πεις εδω και χρόνια κλειδωσαν εξυπνάκια.

**Comment by iptvnikolas** [comment]
ΡΙΚ, Ωμέγα και Σίγμα έχουν token. Τα υπόλοιπα κυπριακά είναι κλειδωμένα. Αλλά το l2.cloudskep.com/ant1cm2/abr/chunks.m3u8 ιδιώτης το έχει

**Comment by ghost** [comment]
Εδώ κι χρόνια έχω υβριδική τηλεόραση του ΡΙΚ.

**Comment by ghost** [comment]
Σήμερα λέω να βγάλω όλα τα ΡΙΚ και τα Sigma, Capital, One CY, Extra και Smile. Θα αφήσω μόνο ΡΙΚ Sat, Omega και Ant1.

**Comment by ghost** [comment]
Έσβησα τα Star,Open και όλα τα κυπριακά πλην ΡΙΚ Sat,Omega και Ant1.

**Comment by ghost** [comment]
Το Open λόγω αγανάκτησης και τεχνικών προβλημάτων, το Star λόγω πνευματικών δικαιωμάτων και τα μισά κυπριακά λόγω κλειδωμένων player.

**Comment by komhsgr** [comment]
Παμε ξανα απο την αρχη
Link http://l6.cloudskep.com/tvb6/rik1-1/mpeg.2ts
το συγκεκριμένο link ειναι μεσα απο την σελιδα της υβριδικής τηλεόρασης του ΡΙΚ
Δεν ειχαν geoblock   και το κρυβαμε μηνες, και πηγες εσυ σαν καλος εξυπνακιας και το εδωσες δημόσια
στο IPTV.ORG με αποτέλεσμα να εκμεταλευονται διαφοροι, να το πάρει χαμπάρι το ΡΙΚ και να τα κλειδώσουν.

Πάρτο χαμπάρι κανεις χαζομάρες και δεν ξερεις και ανακατευεσαι απο πάνω. 

Το τί θα κάνεις δε με ενδιαφέρει απλα μαζέψου και μην ασχολησε σε κάτι που δεν ξέρεις.

**Comment by ghost** [comment]
http://l6.cloudskep.com/tvb6/rik1-1/mpeg.2ts κλειδώθηκε

**Comment by ghost** [comment]
Αυτό το συγκεκριμένο link το έσβησα.

**Comment by ghost** [comment]
Σκέφτομαι να σβήσω το λογαριασμό μου στο GitHub και να μην ξαναεμφανίστω γιατί κάνω όλη τη ώρα χαζομάρες.

**Comment by komhsgr** [comment]
να ασχολησε μονο με links μεσα απο τις επισημες σελιδες των καναλιων αυτη ειναι η συμβουλη μου.

**Comment by ghost** [comment]
Λέω να μην ξαναμπώ ποτέ στο github. Οποιαδήποτε link στέλνω θα γράφεται στο pastebin.

**Comment by ghost** [comment]
Στο pastebin κάποια στιγμή θα κάνω λογαριασμό και θα στέλνω τα λινκς από τα επίσημες σελίδες των καναλιών η οποίος η οποία μου ζητήσει καινούργιο λινκ θα το επιβεβαιώνω.

**Comment by komhsgr** [comment]
pastebin να σε ενημερώσω τετοιου ειδους αρχεια τα διαγραφει χωρις να σε ρωτησει.

**Comment by ghost** [comment]
Λες να αρχίσω να στέλνω links μόνο από τις επίσημες ζωντανές ροές? Θα κάνω δύο αρχεία όπου θα ασχολείται μόνο με τις επίσημες ζωντανές ροές. Εσύ κόμη μου θα με ενημερώνεις για τα καινούργια επίσημα ζωντανά λινκς των καναλιών και εγώ θα τα προσθέτω.

**Comment by komhsgr** [comment]
Σβησε το παρον διαολογο σε παρακαλω και ακου την συμβουλη μου,

**Comment by ghost** [comment]
Την ακούω και την δημοσίευα.
Εδώ έγραψα τους κανόνες στα αγγλικά εδώ:
https://raw.githubusercontent.com/iptvnikolas/Nikki-TVM3U8/main/grtv.m3u
Σε άλλο αρχείο θα μπούνε τα "ψευδής" live streamings.

**Comment by ghost** [comment]
Οποιοδήποτε live streaming δεν λειτουργεί θα γράφω δίπλα από το όνομα του κανάλιου την λέξη offline.

**Comment by ghost** [comment]
Κόμη μου θα έχω τα ίδια κανάλια η θα έχω παραπάνω?

**Comment by ghost** [comment]
Κόμη μου ορίστε:
https://raw.githubusercontent.com/iptvnikolas/Nikki-TVM3U8/main/grtv.m3u
Τσεκαρε το και βρες εντυπώσεις. Ναι είναι τα κανονικά λινκς από τις ιστοσελίδες των ζωντανών ροών.

**Comment by ghost** [comment]
Ο Alpha Κύπρου μου είπε ότι θα επιστρέψει σύντομα εκτός Ελλάδας με το ίδιο λινκ (http://l4.cloudskep.com/alphacyp/acy/playlist.m3u8) αλλά θα περιμένουμε λίγο χρόνο. Τα υπόλοιπα 4 κυπριακά και το ΡΙΚ για να μάθουμε τα σωστά λινκς πρέπει να έρθει η (http://www.lakatamia.tv) στο github για να μας ενημερώνει.

**Comment by komhsgr** [comment]
χθες σου εκανα παρατηρηση εσυ παλι τα δικα σου. Γιατι πηγες στον ALPHA KYΠΡΟΥ τι ηθελες να κερδίσεις? 
 Επισης γιατί ασχολήσε με το εν λογο αθλημα?

**Comment by ghost** [comment]
Μίλησα με τους κύριους του καναλιού και μου είπαν ότι σύντομα θα επανέλθουν κανονικά. Την δέχτηκα την παρατήρηση. Μήπως έβαλα ψεύτικο λινκ???

**Comment by ghost** [comment]
Πρέπει να κλειδωθεί αυτό το θέμα. Δεν αντέχω άλλο πια!

**Comment by komhsgr** [comment]
Απλα σταματα να ασχολησε με το αθλημα, δεν προσφερεις απολυτος τιποτα παρα μονο ζημιες κανεις.

**Comment by ghost** [comment]
Πρέπει να το σταματήσω όντως αυτό το πράγμα. Λέω να μην ασχοληθώ ξανά. Αλλά πρέπει να κλειδωθεί αυτό το θέμα. Άντε δεν μπορώ άλλο πια. Θα σταματήσω να έχω τα ψεύδη live streaming που υπάρχουν και δεν λειτουργούν καθόλου. Κουράστηκα να παλεύω με live streamings που δεν δουλεύουν η κυριολεκτικά οποιαδήποτε υπάρχει. Θέλω να διαγράψω το λογαριασμό αλλά η github δεν με αφήνει.

**Comment by ghost** [comment]
Όντως δεν προσευχα τίποτα. Πρέπει να κόψω το δούλεμα.
